# Generated by Django 4.1.5 on 2023-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0005_alter_category_id_alter_post_body_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snipped',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
